<a href="https://colab.research.google.com/github/SarinaMashreghi/Recommender-Systems/blob/main/recommender_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

##Data

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/ML/books.csv").drop_duplicates()
df

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6805,9788185300535,8185300534,I Am that,Talks with Sri Nisargadatta Maharaj,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0
6806,9788185944609,8185944601,Secrets Of The Heart,NaN,Khalil Gibran,Mysticism,http://books.google.com/books/content?id=XcrVp...,NaN,1993.0,4.08,74.0,324.0
6807,9788445074879,8445074873,Fahrenheit 451,NaN,Ray Bradbury,Book burning,NaN,NaN,2004.0,3.98,186.0,5733.0
6808,9789027712059,9027712050,The Berlin Phenomenology,NaN,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0
6809,9789042003408,9042003405,'I'm Telling You Stories',Jeanette Winterson and the Politics of Reading,Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,10.0

In [ ]:
df.columns

Index(['isbn13', 'isbn10', 'title', 'subtitle', 'authors', 'categories',
       'thumbnail', 'description', 'published_year', 'average_rating',
       'num_pages', 'ratings_count'],
      dtype='object')

In [ ]:
categories = pd.factorize(df["categories"])
categories

(array([  0,   1,   2, ..., 498,  64,  68]),
 Index(['Fiction', 'Detective and mystery stories', 'American fiction',
        'Christian life', 'Authors, English', 'Africa, East',
        'Hyland, Morn (Fictitious character)', 'Adventure stories',
        'Arthurian romances', 'Fantasy fiction',
        ...
        'Boats and boating', 'People with social disabilities',
        'Minimal brain dysfunction in children', 'Spiritual life', 'Meditation',
        'Gay men', 'Christian fiction', 'Napoleonic Wars, 1800-1815',
        'Indic fiction (English)', 'Mysticism'],
       dtype='object', length=567))

In [ ]:
df = df.dropna(subset=["description", "thumbnail", "average_rating", "authors"])
df

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6803,9788173031014,8173031010,Journey to the East,NaN,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0
6804,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,NaN,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0
6805,9788185300535,8185300534,I Am that,Talks with Sri Nisargadatta Maharaj,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0
6808,9789027712059,9027712050,The Berlin Phenomenology,NaN,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0
6809,9789042003408,9042003405,'I'm Telling You Stories',Jeanette Winterson and the Politics of Reading,Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,10.0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['description'])

type(tfidf_matrix), tfidf_matrix.shape

(scipy.sparse.csr.csr_matrix, (6236, 29679))

##KMeans Clustering

In [ ]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=10).fit(tfidf_matrix)

In [ ]:
sample1 = df["description"][0]
sample1_cat = df["categories"][0]
sample1, sample1_cat

('A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.',
 'Fiction')

In [ ]:
sample2 = df["description"][1]
sample2_cat = df["categories"][1]
sample2, sample2_cat

("A new 'Christie for Christmas' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. 'Supposing I were to come down one morning and find a dead body in the library, what should I do?' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI",
 'Detective and mystery stories')

In [ ]:
pred_list = [sample1, sample2]
kmeans.predict(tfidf.transform(pred_list))

array([ 0, 13], dtype=int32)

In [ ]:
clusters = kmeans.predict(tfidf_matrix)
clusters

array([6, 6, 7, ..., 5, 3, 0], dtype=int32)

In [ ]:
df["cluster"] = clusters
df

<ipython-input-11-fddb6d9e6968>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["cluster"] = clusters

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,cluster
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,6
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,6
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0,7
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,7
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6803,9788173031014,8173031010,Journey to the East,NaN,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,5
6804,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,NaN,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,5
6805,9788185300535,8185300534,I Am that,Talks with Sri Nisargadatta Maharaj,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,5
6808,9789027712059,9027712050,The Berlin Phenomenology,NaN,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,3
6809,9789042003408,9042003405,'I'm Telling You Stories',Jeanette Winterson and the Politics of Reading,Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,10.0,0

In [ ]:
df.to_csv("/content/drive/MyDrive/ML/clustered_data_10c.csv")

In [ ]:
df.loc[df["cluster"]==9]

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,cluster
9,9780006472612,0006472613,Master of the Game,NaN,Sidney Sheldon,Adventure stories,http://books.google.com/books/content?id=TkTYp...,Kate Blackwell is an enigma and one of the mos...,1982.0,4.11,489.0,43540.0,9
30,9780006514855,0006514855,Girls' Night in,NaN,Jessica Adams;Chris Manby;Fiona Walker,American fiction,http://books.google.com/books/content?id=xLwHH...,'Girls' Night In' features stories about growi...,2000.0,3.26,586.0,140.0,9
32,9780006550433,0006550436,The Bonesetter's Daughter,NaN,Amy Tan,China,http://books.google.com/books/content?id=4KHT6...,Tells the story of three generations of Chines...,2001.0,3.98,352.0,414.0,9
42,9780007116263,0007116268,"The Lord of the Rings, the Return of the King",Visual Companion,Jude Fisher,Imaginary wars and battles,http://books.google.com/books/content?id=kNBnQ...,A visual guide to the third in the Lord of the...,2003.0,4.59,72.0,22.0,9
63,9780007135653,0007135653,The Lord of the Rings,The Art of The Return of the King,Gary Russell,Characters and characteristics in motion pictures,http://books.google.com/books/content?id=oEZ6A...,With complete access to artwork created over a...,2004.0,4.54,224.0,28.0,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6769,9781933110332,1933110333,A Matter of Trust,NaN,Radclyffe,Fiction,http://books.google.com/books/content?id=yb5UJ...,"Michael Lassiter hires J.T. Sloan, a security ...",2006.0,4.20,240.0,910.0,9
6775,9781933615097,1933615095,The Best of America's Test Kitchen 2007,"The Year's Best Recipes, Equipment Reviews, an...",America's Test Kitchen,Cooking,http://books.google.com/books/content?id=tQ97A...,Presents nearly one thousand recipes--from app...,2006.0,4.34,312.0,185.0,9
6780,9781933771175,1933771178,Coffee at Luke's,An Unauthorized Gilmore Girls Gabfest,Jennifer Crusie,Performing Arts,http://books.google.com/books/content?id=ZWW72...,"In the fall of 2000,Gilmore Girls premiered on...",2007.0,3.55,197.0,897.0,9
6793,9784766113389,4766113381,How to Draw Manga,Girls' Life Illustration File,Kazuko Tadano,Art,http://books.google.com/books/content?id=N3s3G...,This volume was inspired by young women workin...,2003.0,4.14,132.0,65.0,9
6796,9784770028037,4770028032,日本語の感情表現集,Expressing Emotions in Japanese,村上真美子,Foreign Language Study,http://books.google.com/books/content?id=ST7ru...,This is a student's guide to the expression of...,2002.0,3.54,176.0,27.0,9

In [ ]:
possible_choices = df.loc[df["cluster"]==0]
possible_choices.iloc[[0]]

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,cluster
12,9780006482079,0006482074,Warhost of Vastmark,NaN,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0f...,"Tricked once more by his wily half-brother, Ly...",1995.0,4.03,522.0,2966.0,0

In [ ]:
import random

NUM_CLUSTER = 10
def random_suggestion(df, prob_list, n_clusters=NUM_CLUSTER):
  clusters = np.arange(n_clusters)
  chosen_cluster = np.random.choice(clusters, p=prob_list/(prob_list.sum()))
  possible_choices = df.loc[df["cluster"]==chosen_cluster]
  recom_book = random.randint(0, len(possible_choices))
  return possible_choices.iloc[recom_book], chosen_cluster

prob = np.ones(NUM_CLUSTER)
random_suggestion(df, prob)[0]["title"], random_suggestion(df, prob)[0]["description"], random_suggestion(df, prob)[0]["cluster"]

('The Brotherhood of the Rose', 'A practical guide to interpreting dreams.', 8)

In [ ]:
# NUM_CLUSTERS = 20

# def get_prefrences(df, num_questions=20):
#   liked_clusters = np.zeros(NUM_CLUSTERS)

#   for i in range(num_questions):
#     rand_book = random_suggestion(df)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

##Recommendation based on description (tf-idf)

In [ ]:
from sklearn.metrics.pairwise import linear_kernel


def get_rec_tfidf(df, book, cluster):

  same_cluster_df = df.loc[df["cluster"]==cluster].reset_index()
  
  tfidf = TfidfVectorizer(stop_words='english')
  tfidf_matrix = tfidf.fit_transform(same_cluster_df['description'])

  cosine_sim_tfidf = linear_kernel(tfidf_matrix, tfidf_matrix)

  # print(same_cluster_df)
  indices = pd.Series(same_cluster_df.index, same_cluster_df['title']).drop_duplicates()
  # print(indices)

  idx = indices[book]
  # print(idx)

  sim_scores = list(enumerate(cosine_sim_tfidf[idx]))
        
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

  sim_scores = sim_scores[1:11]

  movie_indices = [i[0] for i in sim_scores]

  return same_cluster_df['title'].iloc[movie_indices]

rand_book, cluster = random_suggestion(df, 20)
print(f"liked book: {rand_book['title']}") 
get_rec_tfidf(df, rand_book["title"], cluster)

liked book: On a pale horse

284                           Echoes of the Marseillaise
123                                Armageddon's Children
292                                           Armageddon
22     The Chronicles of Narnia Movie Tie-in Edition ...
118                              The demon-haunted world
143                                       Oryx and Crake
324                                        The Last Days
114                                  Chasing the Monsoon
230                                  The Denial of Death
217                            New Worlds, Ancient Texts
Name: title, dtype: object

##Recommendation based on author and category

In [ ]:
df = df.dropna(subset=["authors"])
df

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,cluster,metadata
0,9780002005883,0002005883,Gilead,NaN,marilynnerobinson,fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,1,m a r i l y n n e r o b i n s o n f i c t i o n
1,9780002261982,0002261987,Spider's Web,A Novel,charlesosborne;agathachristie,detectiveandmysterystories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,18,c h a r l e s o s b o r n e ; a g a t h a c h ...
2,9780006163831,0006163831,The One Tree,NaN,stephenr.donaldson,americanfiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0,1,s t e p h e n r . d o n a l d s o n a m e r i ...
3,9780006178736,0006178731,Rage of angels,NaN,sidneysheldon,fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,4,s i d n e y s h e l d o n f i c t i o n
4,9780006280897,0006280897,The Four Loves,NaN,clivestapleslewis,christianlife,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,4,c l i v e s t a p l e s l e w i s c h r i s t ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6803,9788173031014,8173031010,Journey to the East,NaN,hermannhesse,adventurestories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,4,h e r m a n n h e s s e a d v e n t u r e s t ...
6804,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,NaN,robinsharma,health&fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,4,r o b i n s h a r m a h e a l t h & f i t n e s s
6805,9788185300535,8185300534,I Am that,Talks with Sri Nisargadatta Maharaj,srinisargadattamaharaj;sudhakars.dikshit,philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,12,s r i n i s a r g a d a t t a m a h a r a j ; ...
6808,9789027712059,9027712050,The Berlin Phenomenology,NaN,georgwilhelmfriedrichhegel,history,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,6,g e o r g w i l h e l m f r i e d r i c h h e ...
6809,9789042003408,9042003405,'I'm Telling You Stories',Jeanette Winterson and the Politics of Reading,helenagrice;timwoods,literarycriticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,10.0,15,h e l e n a g r i c e ; t i m w o o d s l i t ...

In [ ]:
def clean_data(x):
    if isinstance(x, list):
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        #Check if director exists. If not, return empty string
        if isinstance(x, str):
            return str.lower(x.replace(" ", ""))
        else:
            return ''

features = ['authors', 'categories']

for feature in features:
    df[feature] = df[feature].apply(clean_data)

<ipython-input-115-9f7157bbb8a4>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature] = df[feature].apply(clean_data)

In [ ]:
def make_metadata(x):
    return ''.join(x['authors']) + ' ' + ''.join(x['categories']) 
df['metadata'] = df.apply((make_metadata), axis=1)

In [ ]:
df[["authors", "categories"]]

                                       authors                  categories
0                            marilynnerobinson                     fiction
1                charlesosborne;agathachristie  detectiveandmysterystories
2                           stephenr.donaldson             americanfiction
3                                sidneysheldon                     fiction
4                            clivestapleslewis               christianlife
...                                        ...                         ...
6803                              hermannhesse            adventurestories
6804                               robinsharma              health&fitness
6805  srinisargadattamaharaj;sudhakars.dikshit                  philosophy
6808                georgwilhelmfriedrichhegel                     history
6809                      helenagrice;timwoods           literarycriticism

[6293 rows x 2 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def get_rec_CV(df, book, cluster):

  same_cluster_df = df.loc[df["cluster"]==cluster].reset_index()
  
  count = CountVectorizer(stop_words='english')
  count_matrix = count.fit_transform(same_cluster_df['metadata'])
  # print(count_matrix)

  cosine_sim_CV = cosine_similarity(count_matrix, count_matrix)
  # print(cosine_sim_CV)

  # print(same_cluster_df)
  indices = pd.Series(same_cluster_df.index, same_cluster_df['title']).drop_duplicates()
  # print(indices)

  idx = indices[book]
  # print(idx)

  sim_scores = list(enumerate(cosine_sim_CV[idx]))
        
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

  sim_scores = sim_scores[1:11]

  movie_indices = [i[0] for i in sim_scores]
 

  return same_cluster_df.iloc[movie_indices]

In [ ]:
count = CountVectorizer(stop_words='english')
rand_book, cluster = random_suggestion(df, 20)
print(f"liked book: {rand_book['title']}") 
suggestions = get_rec_CV(df, rand_book["title"], cluster)
suggestions
# print(rand_book["metadata"])
# print(suggestions["metadata"])
# print(cosine_similarity(count.fit_transform(rand_book[["metadata"]]), count.fit_transform(suggestions[["metadata"]])))

liked book: The Sword and the Shield

,index,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,cluster,metadata
36,1400,9780306804984,0306804980,Hannibal,Enemy Of Rome,leonardcottrell,history,http://books.google.com/books/content?id=TZLSt...,"In the year 216 B.C., Hannibal of Carthage, fa...",1992.0,3.89,248.0,128.0,7,leonardcottrell history
103,2092,9780375706363,0375706364,Crucible of War,The Seven Years' War and the Fate of Empire in...,fredanderson,history,http://books.google.com/books/content?id=jyuMq...,"Demonstrating that the decisive ""Seven Years' ...",2000.0,4.15,912.0,2968.0,7,fredanderson history
118,2129,9780375727382,0375727388,"Salonica, City of Ghosts","Christians, Muslims, and Jews, 1430-1950",markmazower,history,http://books.google.com/books/content?id=c8agA...,A vivid narrative history captures the multicu...,2006.0,4.25,544.0,703.0,7,markmazower history
165,3107,9780452288195,0452288193,War and Peace and War,The Rise and Fall of Empires,peterturchin,history,http://books.google.com/books/content?id=cOXJj...,Argues that the key to the formation of an emp...,2007.0,4.15,416.0,252.0,7,peterturchin history
168,3283,9780517884546,0517884542,The Orion Mystery,Unlocking the Secrets of the Pyramids,robertbauval,history,http://books.google.com/books/content?id=XLSer...,"Drawing on more than a decade of research, thi...",1994.0,3.93,352.0,1076.0,7,robertbauval history
179,3800,9780670037605,0670037605,Mayflower,"A Story of Courage, Community, and War",nathanielphilbrick,history,http://books.google.com/books/content?id=qk9AX...,A history of the Pilgrim settlement of New Eng...,2006.0,3.87,461.0,29543.0,7,nathanielphilbrick history
196,4056,9780679781172,067978117X,The Living and the Dead,Robert McNamara and Five Lives of a Lost War,paulhendrickson,history,http://books.google.com/books/content?id=nfxvD...,A critical study of Secretary of Defense Rober...,1997.0,4.03,448.0,129.0,7,paulhendrickson history
204,4350,9780743252218,0743252217,Sea of Thunder,Four Commanders and the Last Great Naval Campa...,evanthomas,history,http://books.google.com/books/content?id=je8ds...,A suspenseful account of the Battle of Leyte G...,2006.0,4.11,415.0,2332.0,7,evanthomas history
246,5037,9780805078428,0805078428,"The Historical Atlas of New York City, Second ...",A Visual Celebration of 400 Years of New York ...,erichomberger,history,http://books.google.com/books/content?id=Q8Egs...,A richly illustrated reference chronicles the ...,2005.0,4.05,192.0,290.0,7,erichomberger history
255,5222,9780812969702,0812969707,A War Like No Other,How the Athenians And Spartans Fought the Pelo...,victordavishanson,history,http://books.google.com/books/content?id=v7q94...,A colorful history of the Peloponnesian War an...,2006.0,4.11,397.0,1601.0,7,victordavishanson history

##Finding proportion weights based on cosine similarity and ratings

In [ ]:
from numpy.linalg import norm

def get_cos_sims_tfidf(book, similar_books):
  tfidf = TfidfVectorizer(stop_words='english')
  tfidf_matrix = tfidf.fit_transform(same_cluster_df['description']) 
  cos_sim = np.dot(A,B)/(norm(A, axis=1)*norm(B))
  #????

In [ ]:
from numpy.lib.function_base import average
def get_final_recs(df, ratio=1):
  rand_book, cluster = random_suggestion(df, 20)
  suggestions_1 = get_rec_CV(df, rand_book["title"], cluster)
  suggestions_2 = get_rec_CV(df, rand_book["title"], cluster)
  all_recs = pd.concat([suggestions_1, suggestions_2])

  probs = all_recs["average_rating"]/(all_recs["average_rating"].sum())

  final_recs = []
  for i in range(ratio):
    final_recs.append(np.random.choice(all_recs, p=probs))



  return final_recs

get_final_recs(df)

ValueError: ignored